FROM registry.access.redhat.com/ubi8/ubi:8.0

MAINTAINER Red Hat Training <training@redhat.com>

# DocumentRoot for Apache
ENV DOCROOT=/var/www/html
RUN  yum install -y --disableplugin=subscription-manager httpd 
RUN  yum clean all --disableplugin=subscription-manager -y 
RUN  echo "Hello from the httpd-parent container!" > ${DOCROOT}/index.html
RUN  date > ./info.html


EXPOSE 80

# Run as the root user
USER root



# Launch httpd
CMD /usr/sbin/httpd -DFOREGROUND